language: node_js
node_js:
  - "7"
dist: trusty
sudo: true

addons:
  chrome: stable

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn test

deploy:
  provider: script
  skip_cleanup: true
  script: node_modules/.bin/ember deploy production --activate --verbose
